const { chromium } = require('playwright');
const { generateLinkedInPost, generateHROutreach } = require('../outreach/content');
const UserConfig = require('../../models/UserConfig');

/**
 * Automatically logs into LinkedIn (requires existing session cookie or data dir),
 * and creates a new post on the timeline.
 * @param {string} topic The topic to post about today based on your internship learning.
 */
async function autoPostToLinkedIn(topic) {
  // Generate the actual post content using Gemini 2.5
  const postContent = await generateLinkedInPost(topic);
  if (!postContent) return;

  console.log("Automatically posting to LinkedIn...");
  console.log("Drafted Content:", postContent);

  const config = await UserConfig.findOne();
  const browser = await chromium.launch({ headless: true });
  const context = await browser.newContext();

  if (config && config.linkedinCookie) {
    await context.addCookies([{
      name: 'li_at',
      value: config.linkedinCookie,
      domain: '.www.linkedin.com',
      path: '/',
      httpOnly: true,
      secure: true,
      sameSite: 'None'
    }]);
  }

  const page = await context.newPage();

  try {
    // Navigate to LinkedIn feed
    await page.goto('https://www.linkedin.com/feed/', { waitUntil: 'domcontentloaded' });

    // Look for the "Start a post" button
    const startPostBtn = page.locator('button:has-text("Start a post")');
    if (await startPostBtn.count() > 0) {
      await startPostBtn.click();
      
      // Wait for the modal text area to appear
      await page.waitForSelector('.ql-editor', { state: 'visible' });
      const editorialContainer = page.locator('.ql-editor');
      
      // Type out the AI-generated post slowly, acting like a human
      await editorialContainer.fill(postContent);
      
      // Look for the "Post" button and click it to publish
      // await page.locator('button:has-text("Post")').click(); // Commented out to prevent accidental publishing

      console.log("Success! Automated post drafted (and ready to be published).");
    }
  } catch (err) {
    console.error("Error auto-posting to LinkedIn:", err);
  } finally {
    await browser.close();
  }
}

/**
 * Automatically routes to a recruiter's LinkedIn profile and sends a personalized 
 * connection request note generated by Gemini.
 * @param {string} hrProfileUrl 
 * @param {string} hrName 
 * @param {string} companyName 
 * @param {string} roleName 
 */
async function autoMessageHR(hrProfileUrl, hrName, companyName, roleName) {
  // Generate a customized outreach message utilizing Gemini 2.5 flash
  const outreachNote = await generateHROutreach(hrName, companyName, roleName);
  
  if (!outreachNote) return;

  const config = await UserConfig.findOne();
  const browser = await chromium.launch({ headless: true });
  const context = await browser.newContext();

  if (config && config.linkedinCookie) {
    await context.addCookies([{
      name: 'li_at',
      value: config.linkedinCookie,
      domain: '.www.linkedin.com',
      path: '/',
      httpOnly: true,
      secure: true,
      sameSite: 'None'
    }]);
  }

  const page = await context.newPage();

  try {
    await page.goto(hrProfileUrl, { waitUntil: 'domcontentloaded' });

    // Click "Connect" or "More" -> "Connect"
    // (LinkedIn UI changes often, this is a standard approach)
    let connectBtn = page.locator('button[aria-label^="Invite"][aria-label*="to connect"]');
    if (await connectBtn.count() === 0) {
      const moreBtn = page.locator('button[aria-label="More actions"]');
      if (await moreBtn.count() > 0) {
        await moreBtn.click();
        connectBtn = page.locator('div[class*="artdeco-dropdown__content"] button:has-text("Connect")');
      }
    }

    if (await connectBtn.count() > 0) {
      await connectBtn.click();
      
      // Click "Add a note"
      const addNoteBtn = page.locator('button:has-text("Add a note")');
      if (await addNoteBtn.count() > 0) {
        await addNoteBtn.click();
        
        // Type the personalized Gemini HR approach in the text box
        const noteInput = page.locator('textarea[name="message"]');
        await noteInput.fill(outreachNote);

        // Send the invitation
        // await page.locator('button:has-text("Send")').click(); // Disabled for safety
        console.log(`Successfully drafted AI connection request to ${hrName} at ${companyName}.`);
      }
    }
  } catch (err) {
    console.error(`Failed to message HR at ${hrProfileUrl}`, err);
  } finally {
    await browser.close();
  }
}

module.exports = {
  autoPostToLinkedIn,
  autoMessageHR
};
